/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author Usuario
 */
public class Presentacion extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Presentacion() {
        initComponents();
        setLocationRelativeTo(null); //funcion para mostrar en el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgraund = new javax.swing.JPanel();
        UNI = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();
        Tablas = new javax.swing.JButton();
        PaS = new javax.swing.JButton();
        SaP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backgraund.setPreferredSize(new java.awt.Dimension(420, 640));

        UNI.setText("<html><b>UNIVERSIDAD NACIONAL DE INGENIERÍA<br><center>Programa de Matemáticas Discretas<html>");

        Autor.setText("By Edwing JF © ");

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Logo_UNI.jpg"))); // NOI18N

        Tablas.setText("Tablas  de verdad");
        Tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablasActionPerformed(evt);
            }
        });

        PaS.setText("<html>Proposiciones a<br><center>Simbolos<html>");
        PaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaSActionPerformed(evt);
            }
        });

        SaP.setText("<html>Simbolos a<br><center>Proposiciones<html>");
        SaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaPActionPerformed(evt);
            }
        });

        jLabel1.setText("<html><b><center>Lógica y <br>demostraciones<html>");

        javax.swing.GroupLayout BackgraundLayout = new javax.swing.GroupLayout(Backgraund);
        Backgraund.setLayout(BackgraundLayout);
        BackgraundLayout.setHorizontalGroup(
            BackgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgraundLayout.createSequentialGroup()
                .addGroup(BackgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgraundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgraundLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(UNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgraundLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Tablas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(SaP, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgraundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Img)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgraundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaS, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
        );
        BackgraundLayout.setVerticalGroup(
            BackgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(BackgraundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Autor)
                .addContainerGap())
            .addGroup(BackgraundLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(UNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgraundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(PaS, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(Backgraund, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 610, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablasActionPerformed
        Tablas mover = new Tablas(); //creamos unibjeto del tipo ventana tablas
        mover.setVisible(true); // con esta sentencia nos cambiamos de ventana
        this.setVisible(false); //ahora con el this indicamos que estamos en la presentacion y con el paramtero false ocultamos
    }//GEN-LAST:event_TablasActionPerformed

    private void PaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaSActionPerformed
        PaS mover = new PaS();
        mover.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PaSActionPerformed

    private void SaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaPActionPerformed
        SaP mover = new SaP();
        mover.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SaPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JPanel Backgraund;
    private javax.swing.JLabel Img;
    private javax.swing.JButton PaS;
    private javax.swing.JButton SaP;
    private javax.swing.JButton Tablas;
    private javax.swing.JLabel UNI;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
